"""Fail closed: only advertise pages whose exact generated bytes are public."""
import hashlib
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import Request, urlopen

ORIGIN = 'https://dingodoronetech.eu.org'


def verify_post(post):
    path = post['url']
    if (not path.startswith(('/posts/', '/publications/')) and path != '/alarme-pg107.html') or '..' in path or '?' in path:
        raise ValueError('Invalid publication URL')
    request = Request(ORIGIN + path, headers={'Cache-Control': 'no-cache', 'User-Agent': 'Dingodor-publication-check/1.0'})
    with urlopen(request, timeout=60) as response:
        body = response.read()
        if response.status != 200 or response.geturl() != ORIGIN + path:
            raise RuntimeError('Page unavailable: ' + path)
    if hashlib.sha256(body.replace(b'\r\n', b'\n')).hexdigest() != post['sha256']:
        raise RuntimeError('Public page does not match generated article: ' + path)


def verify_manifest(candidate, previous=None):
    posts = json.loads(Path(candidate).read_text(encoding='utf-8'))['posts']
    # A previous manifest was itself gated by this check. Recheck new/changed pages.
    old = {}
    if previous and Path(previous).exists():
        old = {p['url']: p['sha256'] for p in json.loads(Path(previous).read_text(encoding='utf-8'))['posts']}
    pending = [p for p in posts if old.get(p['url']) != p['sha256']]
    def retry(post):
        for attempt in range(4):
            try:
                verify_post(post)
                return
            except (OSError, RuntimeError):
                if attempt == 3:
                    raise
                time.sleep(2 ** attempt)
    with ThreadPoolExecutor(max_workers=4) as pool:
        list(pool.map(retry, pending))
    print(f'{len(pending)} new or changed public pages verified')


if __name__ == '__main__':
    verify_manifest(*sys.argv[1:])
