"""Fail closed: only advertise pages whose exact generated bytes are public."""
import hashlib
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

ORIGIN = 'https://dingodoronetech.eu.org'
# CDN propagation can lag behind a successful Pages deployment.
RETRY_DELAYS = (5, 10, 20, 30, 45, 60, 60, 60)


def verify_post(post):
    path = post['url']
    if (not path.startswith(('/posts/', '/publications/')) and path != '/alarme-pg107.html') or '..' in path or '?' in path:
        raise ValueError('Invalid publication URL')
    request = Request(ORIGIN + path, headers={'Cache-Control': 'no-cache', 'User-Agent': 'Dingodor-publication-check/1.0'})
    with urlopen(request, timeout=60) as response:
        body = response.read()
        if response.status != 200 or response.geturl() != ORIGIN + path:
            raise RuntimeError('Page unavailable: ' + path)
    if hashlib.sha256(body.replace(b'\r\n', b'\n')).hexdigest() != post['sha256']:
        raise RuntimeError('Public page does not match generated article: ' + path)


def verify_with_retry(post):
    """Wait for propagation without accepting a missing or outdated page."""
    url = ORIGIN + post['url']
    attempts = len(RETRY_DELAYS) + 1
    for attempt in range(attempts):
        try:
            verify_post(post)
            return
        except (OSError, RuntimeError) as error:
            # Authentication and other permanent client errors need intervention.
            retryable = not isinstance(error, HTTPError) or (
                error.code in {404, 408, 429} or 500 <= error.code < 600
            )
            if not retryable or attempt == attempts - 1:
                raise RuntimeError(
                    f'Publication verification failed for {url} after '
                    f'{attempt + 1} attempt(s): {error}. '
                    'The article was not added to the index. '
                    'Fix the error or rerun the failed publication job.'
                ) from error
            delay = RETRY_DELAYS[attempt]
            print(f'Waiting for {url}: {error}; '
                  f'retrying in {delay}s ({attempt + 1}/{attempts})',
                  flush=True)
            time.sleep(delay)


def verify_manifest(candidate, previous=None):
    posts = json.loads(Path(candidate).read_text(encoding='utf-8'))['posts']
    # A previous manifest was itself gated by this check. Recheck new/changed pages.
    old = {}
    if previous and Path(previous).exists():
        old = {p['url']: p['sha256'] for p in json.loads(Path(previous).read_text(encoding='utf-8'))['posts']}
    pending = [p for p in posts if old.get(p['url']) != p['sha256']]
    with ThreadPoolExecutor(max_workers=4) as pool:
        list(pool.map(verify_with_retry, pending))
    print(f'{len(pending)} new or changed public pages verified')


if __name__ == '__main__':
    verify_manifest(*sys.argv[1:])
