'use strict';
const REPO='dingodorone/dingodor-one-tech-drafts', API='https://api.github.com/repos/'+REPO;
const $=id=>document.getElementById(id);
let token='', current=null, draft={}, entries=[], range=null, busy=false, imageMode='body', editingChip=null;
const blobs=new Set();
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
function encode(text){const bytes=new TextEncoder().encode(text);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary);}
function decode(text){const binary=atob(text.replace(/\s/g,''));return new TextDecoder().decode(Uint8Array.from(binary,c=>c.charCodeAt(0)));}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...options.headers},cache:'no-store'});if(!r.ok){if(r.status===409||r.status===422)throw Error('Le brouillon a changé ou ce nom existe déjà. Rechargez la liste avant de réessayer ; votre texte reste dans l’éditeur.');if(r.status===401||r.status===403||r.status===404)throw Error('Accès refusé. Vérifiez la clé, son expiration et les droits sur le dépôt privé.');throw Error('GitHub ne répond pas correctement ('+r.status+'). Réessayez.');}return r.status===204?null:r.json();}
async function task(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function remember(){const selection=getSelection();if(selection.rangeCount&&$('body').contains(selection.anchorNode))range=selection.getRangeAt(0).cloneRange();}
function restore(){if(range&&$('body').contains(range.commonAncestorContainer)){const sel=getSelection();sel.removeAllRanges();sel.addRange(range);}else{$('body').focus();const r=document.createRange();r.selectNodeContents($('body'));r.collapse(false);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);}}
function insert(node){restore();const sel=getSelection(),r=sel.getRangeAt(0);r.deleteContents();r.insertNode(node);const next=document.createElement('p');next.append(document.createElement('br'));node.after(next);r.setStart(next,0);r.collapse(true);sel.removeAllRanges();sel.addRange(r);range=r.cloneRange();changed();}
function changed(){$('save-state').textContent='Modifications à enregistrer';}
function filteredHTML(html){const root=new DOMParser().parseFromString(html,'text/html').body;root.querySelectorAll('script,style,iframe,object,embed,svg,math,form,input,button,link,meta,video,audio').forEach(n=>n.remove());root.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes]){if(a.name.startsWith('on')||!['href','src','alt','title','class','style','colspan','rowspan','width','height','start'].includes(a.name))n.removeAttribute(a.name);if(['href','src'].includes(a.name)&&! /^(https?:\/\/|mailto:|\/media\/|\/article-media\/)/i.test(a.value))n.removeAttribute(a.name);}if(n.hasAttribute('style')&&/url\s*\(|expression|@import/i.test(n.getAttribute('style')))n.removeAttribute('style');});return root.innerHTML;}
function chip(item){const figure=document.createElement('figure');figure.className='video-chip';figure.contentEditable='false';figure.dataset.video=JSON.stringify(item);const title=document.createElement('strong');title.textContent='▶ Vidéo';const source=document.createElement('span');source.textContent=item.file?item.file.split('/').pop():item.url;figure.append(title,source);if(item.caption){const c=document.createElement('figcaption');c.textContent=item.caption;figure.append(c);}const edit=document.createElement('button');edit.type='button';edit.textContent='Modifier';edit.onclick=()=>openVideo(figure);const remove=document.createElement('button');remove.type='button';remove.textContent='Retirer';remove.onclick=()=>{figure.remove();changed();};figure.append(edit,remove);return figure;}
function getData(){const copy=$('body').cloneNode(true),videos=[];copy.querySelectorAll('.video-chip').forEach(n=>{const item=JSON.parse(n.dataset.video);delete item.position;delete item.paragraph;videos.push(item);const p=document.createElement('p');p.textContent='[[video:'+videos.length+']]';n.replaceWith(p);});copy.querySelectorAll('img[data-private-src]').forEach(img=>{img.src=img.dataset.privateSrc;img.removeAttribute('data-private-src');});return {...draft,title:$('title').value.trim(),excerpt:$('excerpt').value,notes:$('notes').value,body:copy.innerHTML,videos};}
function signature(){return JSON.stringify(getData());}
let savedSignature='';function unsaved(){return $('workspace').hidden?false:signature()!==savedSignature;}
function clearBlobs(){for(const url of blobs)URL.revokeObjectURL(url);blobs.clear();}
async function privateImages(){for(const img of $('body').querySelectorAll('img')){const path=img.getAttribute('src');if(!path||!path.startsWith('/media/'))continue;img.dataset.privateSrc=path;try{const file=await api('/contents/'+path.slice(1));const bytes=Uint8Array.from(atob(file.content.replace(/\s/g,'')),c=>c.charCodeAt(0));const ext=path.split('.').pop().toLowerCase(),mime={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif'}[ext];const url=URL.createObjectURL(new Blob([bytes],{type:mime}));blobs.add(url);img.src=url;}catch{img.alt=img.alt||'Image privée — aperçu indisponible';}}}
function paint(data){clearBlobs();draft=structuredClone(data);$('title').value=data.title||'';$('excerpt').value=data.excerpt||'';$('notes').value=data.notes||'';$('body').innerHTML=filteredHTML(data.body||'');range=null;for(const [i,item] of (data.videos||[]).entries()){const marker='[[video:'+(i+1)+']]';const walker=document.createTreeWalker($('body'),NodeFilter.SHOW_TEXT);let found=null;while(walker.nextNode()){if(walker.currentNode.textContent.includes(marker)){found=walker.currentNode;break;}}const node=chip(item);if(found){const r=document.createRange(),offset=found.textContent.indexOf(marker);r.setStart(found,offset);r.setEnd(found,offset+marker.length);r.deleteContents();r.insertNode(node);}else if(item.position==='start')$('body').prepend(node);else if(item.position==='paragraph'){const paragraphs=$('body').querySelectorAll('p');const target=paragraphs[Math.min(Math.max(1,Number(item.paragraph)||1),paragraphs.length)-1];target?target.after(node):$('body').append(node);}else $('body').append(node);}coverLabel();savedSignature=signature();$('save-state').textContent=current?'Brouillon enregistré':'Nouveau brouillon';privateImages();}
function coverLabel(){$('cover-name').textContent=draft.featured_image?draft.featured_image.split('/').pop():'';$('remove-cover').hidden=!draft.featured_image;}
async function refreshList(){entries=await api('/contents/articles?ref=main');if(!Array.isArray(entries))entries=[];drawList();}
function drawList(){const q=$('search').value.toLowerCase();$('drafts').replaceChildren();for(const entry of entries.filter(e=>e.name.endsWith('.json')&&e.name.toLowerCase().includes(q))){const b=document.createElement('button');b.textContent=entry.name.replace(/\.json$/,'').replace(/-/g,' ');b.onclick=()=>task(async()=>{if(unsaved()&&!confirm('Quitter ce brouillon sans enregistrer les modifications ?'))return;const file=await api('/contents/'+entry.path+'?ref=main');current={path:entry.path,sha:file.sha};paint(JSON.parse(decode(file.content)));status('Brouillon ouvert.');});$('drafts').append(b);}}
function slugify(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100).replace(/-$/,'');}
async function save(){const data=getData();if(!data.title||!$('body').textContent.trim())throw Error('Ajoutez un titre et le contenu de l’article.');const savingSignature=signature();const path=current?.path||'articles/'+slugify(data.title)+'.json';if(path==='articles/.json')throw Error('Le titre doit contenir des lettres ou chiffres.');const body={message:'Enregistrer le brouillon depuis l’éditeur Dingodor',content:encode(JSON.stringify(data,null,2)+'\n'),branch:'main'};if(current)body.sha=current.sha;const result=await api('/contents/'+path,{method:'PUT',body:JSON.stringify(body)});current={path,sha:result.content.sha};draft=data;savedSignature=savingSignature;$('save-state').textContent='Brouillon enregistré';status('Enregistré dans vos brouillons privés.');await refreshList();}
async function upload(file,kind){if(!file)throw Error('Choisissez un fichier.');const ext=file.name.split('.').pop().toLowerCase(),allowed=kind==='video'?['mp4','webm']:['png','jpg','jpeg','webp','gif'];if(!allowed.includes(ext))throw Error('Format de fichier non pris en charge.');if(file.size>20*1024*1024)throw Error('Le fichier dépasse 20 Mo. Utilisez un lien pour les longues vidéos.');const path='media/'+crypto.randomUUID()+'.'+ext;const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Impossible de lire le fichier.'));reader.readAsDataURL(file);});await api('/contents/'+path,{method:'PUT',body:JSON.stringify({branch:'main',message:'Importer un média privé depuis l’éditeur',content})});return '/'+path;}
function validVideoURL(value){const url=new URL(value);if(url.protocol!=='https:')throw Error('Utilisez un lien HTTPS.');return url.href;}
function openVideo(existing=null){remember();editingChip=existing;const item=existing?JSON.parse(existing.dataset.video):{};$('video-url').value=item.url||'';$('video-file').value='';$('video-caption').value=item.caption||'';$('video-dialog').showModal();}
async function dispatch(workflow,inputs={}){await save();await api('/actions/workflows/'+workflow+'/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:{payload:JSON.stringify({context:{path:current.path},inputs})}})});status('Demande transmise à GitHub. Le traitement prend quelques minutes ; ce message ne confirme pas encore la mise en ligne.');const a=document.createElement('a');a.href='https://github.com/'+REPO+'/actions/workflows/'+workflow;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Suivre le traitement';$('status').append(document.createElement('br'),a);}
$('login-form').onsubmit=e=>{e.preventDefault();task(async()=>{token=$('token').value.trim();$('token').value='';await refreshList();$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;current=null;paint({body:'<p></p>'});status('Connecté à vos brouillons privés.');});};
$('logout').onclick=()=>{if(unsaved()&&!confirm('Se déconnecter sans enregistrer ?'))return;token='';current=null;entries=[];draft={};clearBlobs();$('drafts').replaceChildren();$('body').replaceChildren();$('title').value='';$('excerpt').value='';$('notes').value='';$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;status('Déconnecté.');};
$('new').onclick=()=>{if(unsaved()&&!confirm('Créer un article sans enregistrer le précédent ?'))return;current=null;paint({body:'<p></p>'});$('title').focus();};
$('search').oninput=drawList;for(const id of ['body','title','excerpt','notes'])$(id).addEventListener('input',changed);
$('body').addEventListener('keyup',remember);$('body').addEventListener('mouseup',remember);
$('body').addEventListener('paste',e=>{e.preventDefault();const data=e.clipboardData;restore();document.execCommand('insertHTML',false,filteredHTML(data.getData('text/html')||data.getData('text/plain').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\n/g,'<br>')));changed();});
document.querySelectorAll('.toolbar button').forEach(b=>b.addEventListener('mousedown',e=>{remember();e.preventDefault();}));
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{restore();document.execCommand(b.dataset.command,false);changed();});
document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>{restore();document.execCommand('formatBlock',false,b.dataset.block);changed();});
$('link').onclick=()=>{const value=prompt('Adresse du lien (https://…)');if(!value)return;try{const url=new URL(value);if(!['https:','http:','mailto:'].includes(url.protocol))throw Error('Adresse invalide.');restore();document.execCommand('createLink',false,url.href);changed();}catch(e){status(e.message,true);}};
$('video').onclick=()=>openVideo();$('video-form').onsubmit=e=>{e.preventDefault();task(async()=>{const file=$('video-file').files[0],url=$('video-url').value.trim();if(file&&url)throw Error('Choisissez un lien OU un fichier.');let item={caption:$('video-caption').value};if(file)item.file=await upload(file,'video');else if(url)item.url=validVideoURL(url);else if(editingChip){item={...JSON.parse(editingChip.dataset.video),caption:item.caption};}else throw Error('Ajoutez un lien ou sélectionnez un fichier.');const node=chip(item);if(editingChip){editingChip.replaceWith(node);changed();}else insert(node);$('video-dialog').close();status('Vidéo ajoutée dans le texte. Enregistrez le brouillon pour la conserver.');});};
$('image').onclick=()=>{imageMode='body';$('image-file').click();};$('cover').onclick=()=>{imageMode='cover';$('image-file').click();};$('remove-cover').onclick=()=>{draft.featured_image='';coverLabel();changed();};
$('image-file').onchange=()=>task(async()=>{const file=$('image-file').files[0];if(!file)return;const path=await upload(file,'image');if(imageMode==='cover'){draft.featured_image=path;coverLabel();changed();}else{const figure=document.createElement('figure'),img=document.createElement('img');const blob=URL.createObjectURL(file);blobs.add(blob);img.src=blob;img.dataset.privateSrc=path;img.alt=prompt('Description de l’image',file.name)||'';figure.append(img);insert(figure);}$('image-file').value='';status('Image importée dans votre médiathèque privée.');});
$('save').onclick=()=>task(save);$('preview').onclick=()=>task(()=>dispatch('preview.yml'));
$('publish').onclick=()=>$('publish-dialog').showModal();$('publish-form').onsubmit=e=>{e.preventDefault();task(async()=>{const value=$('publish-date').value;const publish_at=value?new Date(value).toISOString():'';await dispatch('publish.yml',{publish_at});$('publish-dialog').close();});};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
window.addEventListener('beforeunload',e=>{if(unsaved()){e.preventDefault();e.returnValue='';}});
