'use strict';
const RECOVERY='dingodor-editor-recovery-v1', VAULT='dingodor-editor-vault-v1';
let autoTimer=null, selectedImage=null, selectedCell=null, exactFrameURL=null;
const escapeHTML=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tools(title){$('tools-title').textContent=title;$('tools-content').replaceChildren();$('tools-dialog').showModal();return $('tools-content');}
function action(label,fn){const b=document.createElement('button');b.textContent=label;b.type='button';b.onclick=fn;return b;}
function textNode(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
$('tools-close').onclick=()=>$('tools-dialog').close();
function recoveryList(){try{return JSON.parse(localStorage.getItem(RECOVERY)||'[]');}catch{return [];}}
function protectText(){if($('workspace').hidden||!unsaved())return;try{const key=mode+':'+(current?.path||'new'),list=recoveryList().filter(x=>x.key!==key);list.unshift({key,mode,current:current?{...current}:null,data:getData(),date:new Date().toISOString()});localStorage.setItem(RECOVERY,JSON.stringify(list.slice(0,30)));$('recovery-state').textContent='Texte protégé sur ce PC à '+new Date().toLocaleTimeString('fr-FR');}catch{$('recovery-state').textContent='Stockage du PC indisponible : enregistrez sur GitHub.';}}
window.editorChanged=function(){protectText();clearTimeout(autoTimer);if(mode==='articles'&&$('autosave').checked)autoTimer=setTimeout(()=>{if(!busy&&!$('workspace').hidden&&mode==='articles'&&unsaved()&&$('title').value.trim()&&$('body').textContent.trim())task(save);},30000);};
window.editorSaved=()=>{if(unsaved()){protectText();updateSEO();return;}try{const key=mode+':'+(current?.path||'new');localStorage.setItem(RECOVERY,JSON.stringify(recoveryList().filter(x=>x.key!==key)));}catch{};updateSEO();};
$('autosave').onchange=()=>{clearTimeout(autoTimer);if($('autosave').checked)changed();};
window.addEventListener('pagehide',protectText);
$('recover').onclick=()=>{const root=tools('Textes récupérables sur ce PC');const list=recoveryList();if(!list.length)root.append(textNode('p','Aucun texte non enregistré à récupérer.'));for(const item of list){const card=document.createElement('section');card.append(textNode('h3',item.data.title||item.data.message?.slice(0,90)||'Sans titre'),textNode('p',new Date(item.date).toLocaleString('fr-FR')));card.append(action('Récupérer',()=>task(async()=>{if(unsaved()&&!confirm('Remplacer le texte ouvert par cette récupération ?'))return;await switchMode(item.mode);if(mode!==item.mode)return;current=item.current;if(current){try{const file=await api('/contents/'+current.path+'?ref=main');current.sha=file.sha;}catch{current=null;}}paint(item.data);savedSignature='';changed();$('tools-dialog').close();})),action('Supprimer cette récupération',()=>{const next=recoveryList().filter(x=>x.key!==item.key);localStorage.setItem(RECOVERY,JSON.stringify(next));card.remove();}));root.append(card);}};
// Optional encrypted storage: no plaintext credential or passphrase is persisted.
const b64=bytes=>btoa(String.fromCharCode(...bytes));const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function vaultKey(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
function vaultButtons(){const exists=!!localStorage.getItem(VAULT);$('unlock-key').hidden=!exists;$('forget-key').hidden=!exists;}
$('remember-key').onchange=()=>{$('passphrase-label').hidden=!$('remember-key').checked;$('key-passphrase').required=$('remember-key').checked;};
window.editorConnected=async()=>{if(!$('remember-key').checked)return;const pass=$('key-passphrase').value;if(pass.length<12)throw Error('Utilisez une phrase secrète d’au moins 12 caractères.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await vaultKey(pass,salt);const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(token)));localStorage.setItem(VAULT,JSON.stringify({salt:b64(salt),iv:b64(iv),cipher:b64(encrypted)}));$('key-passphrase').value='';vaultButtons();};
$('unlock-key').onclick=()=>{const root=tools('Déverrouiller ma connexion');const input=document.createElement('input');input.type='password';input.autocomplete='current-password';input.placeholder='Votre phrase secrète';input.setAttribute('aria-label','Phrase secrète');root.append(input,action('Déverrouiller',()=>task(async()=>{try{const v=JSON.parse(localStorage.getItem(VAULT));const key=await vaultKey(input.value,unb64(v.salt));const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(v.iv)},key,unb64(v.cipher));token=new TextDecoder().decode(raw);input.value='';await refreshList();$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;current=null;paint(mode==='articles'?{body:'<p></p>'}:{message:'',published:false});$('tools-dialog').close();status('Connexion déverrouillée.');}catch(e){throw Error('Déverrouillage impossible : phrase incorrecte, clé expirée ou accès GitHub indisponible.');}})));};
$('forget-key').onclick=()=>{localStorage.removeItem(VAULT);vaultButtons();status('La copie chiffrée a été oubliée sur ce PC.');};
try{vaultButtons();}catch{}
function updateSEO(){const title=$('seo-title').value||$('title').value,desc=$('seo-description').value||$('excerpt').value,slug=current?.path.split('/').pop().replace(/\.json$/,'')||slugify($('seo-slug').value||$('title').value);$('seo-preview').replaceChildren(textNode('strong',title||'Titre de votre article'),textNode('p','dingodoronetech.eu.org/publications/'+slug+'.html'),textNode('p',desc||'Description de votre article'),textNode('small',title.length+' caractères de titre · '+desc.length+' de description'));}
for(const id of ['title','excerpt','seo-title','seo-description','seo-slug'])$(id).addEventListener('input',updateSEO);
const originalPaint=paint;paint=function(data){originalPaint(data);updateSEO();};
$('history').onclick=()=>task(async()=>{if(!current)throw Error('Enregistrez ou ouvrez un contenu pour voir son historique.');const path=current.path,root=tools('Versions précédentes');root.append(textNode('p','Chargement…'));const commits=await api('/commits?path='+encodeURIComponent(path)+'&per_page=30');root.replaceChildren();for(const commit of commits){const row=document.createElement('section');row.append(textNode('h3',new Date(commit.commit.author.date).toLocaleString('fr-FR')),textNode('p',commit.commit.message));row.append(action('Afficher cette version',()=>task(async()=>{const file=await api('/contents/'+path+'?ref='+commit.sha);const data=JSON.parse(decode(file.content));const preview=document.createElement('pre');preview.textContent=data.title?data.title+'\n\n'+(data.excerpt||'')+'\n\n'+data.body:data.message;preview.className='version-text';row.append(preview);})),action('Restaurer dans l’éditeur',()=>task(async()=>{if(!confirm('Charger cette version dans l’éditeur ? Elle restera à enregistrer et ne sera pas publiée automatiquement.'))return;const file=await api('/contents/'+path+'?ref='+commit.sha);paint(JSON.parse(decode(file.content)));savedSignature='';changed();$('tools-dialog').close();})));root.append(row);}});
$('media-library').onclick=()=>task(async()=>{remember();const root=tools('Médiathèque privée');root.append(textNode('p','Chargement…'));const files=await api('/contents/media?ref=main');root.replaceChildren();const search=document.createElement('input');search.placeholder='Rechercher un fichier';const grid=document.createElement('div');grid.className='media-grid';root.append(search,grid);const draw=()=>{grid.replaceChildren();for(const f of files.filter(x=>/\.(png|jpe?g|webp|gif|mp4|webm)$/i.test(x.name)&&x.name.toLowerCase().includes(search.value.toLowerCase()))){const row=document.createElement('section'),isVideo=/\.(mp4|webm)$/i.test(f.name);row.append(textNode('p',f.name));if(!isVideo){const img=document.createElement('img');img.alt=f.name;img.loading='lazy';row.prepend(img);const observer=new IntersectionObserver(items=>{if(items.some(x=>x.isIntersecting)){observer.disconnect();api('/contents/'+f.path).then(file=>{if(!img.isConnected)return;const ext=f.name.split('.').pop().toLowerCase(),mime={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif'}[ext];const url=URL.createObjectURL(new Blob([unb64(file.content.replace(/\s/g,''))],{type:mime}));blobs.add(url);img.src=url;}).catch(()=>{img.alt='Aperçu indisponible';});}});observer.observe(img);}row.append(action('Insérer',()=>{if(mode==='bons-plans'){if(isVideo){status('Les bons plans acceptent des images.',true);return;}draft.images=[...(draft.images||[]),'/'+f.path];delete draft.preview_products;drawDealImages();changed();}else if(isVideo)insert(chip({file:'/'+f.path,caption:''}));else{const fig=document.createElement('figure'),img=document.createElement('img');fig.className='dt-photo dt-align-center dt-width-100';img.src='/'+f.path;img.alt='';fig.append(img);insert(fig);privateImages();}$('tools-dialog').close();}),...(!isVideo&&mode==='articles'?[action('Image principale',()=>{draft.featured_image='/'+f.path;coverLabel();changed();$('tools-dialog').close();})]:[]));grid.append(row);}};search.oninput=draw;draw();});
$('body').addEventListener('click',e=>{selectedCell=e.target.closest('td,th');if(e.target.tagName!=='IMG')return;selectedImage=e.target;const f=selectedImage.closest('figure');$('image-alt').value=selectedImage.alt;$('image-caption').value=f?.querySelector('figcaption')?.textContent||'';$('image-width').value=Number(f?.className.match(/dt-width-(\d+)/)?.[1]||100);$('image-align').value=f?.className.match(/dt-align-(\w+)/)?.[1]||'center';$('image-crop').value='original';$('image-tools-dialog').showModal();});
$('image-tools-form').onsubmit=e=>{e.preventDefault();task(async()=>{if(!selectedImage||!$('body').contains(selectedImage))throw Error('Sélectionnez une image dans le texte.');let fig=selectedImage.closest('figure');if(!fig){fig=document.createElement('figure');selectedImage.replaceWith(fig);fig.append(selectedImage);}const width=Math.min(100,Math.max(10,Number($('image-width').value)||100));fig.className='dt-photo dt-align-'+$('image-align').value+' dt-width-'+width;selectedImage.alt=$('image-alt').value;let cap=fig.querySelector('figcaption');if($('image-caption').value){if(!cap){cap=document.createElement('figcaption');fig.append(cap);}cap.textContent=$('image-caption').value;}else cap?.remove();if($('image-crop').value!=='original'){const img=new Image();img.src=selectedImage.src;await img.decode();const ratio=$('image-crop').value==='square'?1:16/9;let sw=img.naturalWidth,sh=img.naturalHeight;if(sw/sh>ratio)sw=sh*ratio;else sh=sw/ratio;const canvas=document.createElement('canvas');canvas.width=Math.min(2000,Math.round(sw));canvas.height=Math.round(canvas.width/ratio);canvas.getContext('2d').drawImage(img,(img.naturalWidth-sw)/2,(img.naturalHeight-sh)/2,sw,sh,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('Recadrage impossible.');const path=await upload(new File([blob],'recadrage.jpg',{type:'image/jpeg'}),'image');const url=URL.createObjectURL(lastImageImport?.file||blob);blobs.add(url);selectedImage.src=url;selectedImage.dataset.privateSrc=path;}changed();$('image-tools-dialog').close();});};
$('table-tools').onclick=()=>{if(!selectedCell||!$('body').contains(selectedCell)){status('Cliquez d’abord dans une cellule du tableau.',true);return;}const root=tools('Modifier le tableau sélectionné');const tr=selectedCell.parentElement,table=selectedCell.closest('table');root.append(action('Ajouter une ligne',()=>{const row=document.createElement('tr');for(let i=0;i<tr.cells.length;i++){const td=document.createElement('td');td.textContent='Texte';row.append(td);}tr.after(row);changed();$('tools-dialog').close();}),action('Ajouter une colonne',()=>{const index=selectedCell.cellIndex;for(const row of table.rows){const td=document.createElement(row.cells[0]?.tagName==='TH'?'th':'td');td.textContent='Texte';row.cells[Math.min(index,row.cells.length-1)]?.after(td);}changed();$('tools-dialog').close();}),action('Supprimer la ligne',()=>{tr.remove();if(!table.rows.length)table.remove();changed();$('tools-dialog').close();}),action('Supprimer la colonne',()=>{const index=selectedCell.cellIndex;for(const row of [...table.rows]){row.cells[index]?.remove();if(!row.cells.length)row.remove();}if(!table.rows.length)table.remove();changed();$('tools-dialog').close();}),action('Supprimer le tableau',()=>{table.remove();changed();$('tools-dialog').close();}));};
$('blocks').onclick=()=>{remember();const root=tools('Insérer un bloc');const select=document.createElement('select');for(const [v,t] of [['affiliate','Boutons affiliés France / Belgique'],['callout','Encadré de conseil'],['summary','Sommaire'],['comparison','Tableau comparatif'],['gallery','Galerie de photos'],['disclosure','Mention d’affiliation']]){const o=document.createElement('option');o.value=v;o.textContent=t;select.append(o);}const label=document.createElement('input');label.placeholder='Texte ou titre du bloc';const fr=document.createElement('input');fr.placeholder='Lien affilié Amazon France';const be=document.createElement('input');be.placeholder='Lien affilié Amazon Belgique';const official=document.createElement('input');official.placeholder='Lien boutique officielle (facultatif)';root.append(select,label,fr,be,official,action('Insérer',()=>{try{const node=document.createElement('div');if(select.value==='affiliate'){node.className='dt-buttons';for(const [value,text,country] of [[fr.value,'🇫🇷 Acheter sur Amazon France','fr'],[be.value,'🇧🇪 Acheter sur Amazon Belgique','be'],[official.value,'Voir la boutique officielle','official']]){if(!value)continue;const u=new URL(value);if(u.protocol!=='https:')throw Error('Utilisez des liens HTTPS.');if(country==='fr'&&u.hostname==='www.amazon.fr')u.searchParams.set('tag','dingodor-21');if(country==='be'&&u.hostname==='www.amazon.com.be')u.searchParams.set('tag','dingodor0f-21');const a=document.createElement('a');a.href=u.href;a.rel='nofollow sponsored noopener';a.target='_blank';a.textContent=text;node.append(a);}if(!node.children.length)throw Error('Ajoutez au moins un lien.');}else if(select.value==='callout'){node.className='dt-callout';node.append(textNode('strong',label.value||'À retenir'),textNode('p','Votre conseil ici.'));}else if(select.value==='disclosure'){node.append(textNode('p','Cet article contient des liens affiliés. Dingodor One Tech peut recevoir une commission, sans supplément pour vous.'));}else if(select.value==='summary'){node.className='dt-toc';node.append(textNode('h2','Sommaire'));const ul=document.createElement('ul');$('body').querySelectorAll('h2,h3').forEach((h,i)=>{h.id=h.id||'section-'+(i+1);const li=document.createElement('li'),a=document.createElement('a');a.href='#'+h.id;a.textContent=h.textContent;li.append(a);ul.append(li);});node.append(ul);}else if(select.value==='gallery'){node.className='dt-gallery';node.append(textNode('p','Ajoutez vos photos ici depuis la médiathèque, puis déplacez-les dans ce bloc avec couper/coller.'));}else{const table=document.createElement('table');for(let i=0;i<4;i++){const tr=document.createElement('tr');for(const t of (i===0?['Modèle','Avantages','Limites']:['Modèle','Votre texte','Votre texte']))tr.append(textNode(i===0?'th':'td',t));table.append(tr);}node.append(table);}insert(node);$('tools-dialog').close();}catch(e){status(e.message,true);}}));};
$('publications').onclick=()=>task(async()=>{const root=tools('Publications et programmations');root.append(textNode('p','Chargement…'));const runs=await api('/actions/runs?per_page=20');let queue=[];try{queue=await api('/contents/queue?ref=main');}catch{}root.replaceChildren();root.append(textNode('h3','Articles programmés ou transmis'));for(const entry of queue.filter(x=>x.name.endsWith('.json'))){const row=document.createElement('section');row.append(textNode('p',entry.name.replace('.json','')));root.append(row);const file=await api('/contents/'+entry.path);const q=JSON.parse(decode(file.content));row.replaceChildren(textNode('h3',q.article.title),textNode('p',({queued:'Programmé : ',transmitted:'Transmis au site : ',cancelled:'Programmation annulée : '}[q.state]||q.state)+new Date(q.article.date).toLocaleString('fr-FR')));if(q.state==='transmitted'){const a=document.createElement('a');a.href='/publications/'+q.article.slug+'.html';a.target='_blank';a.textContent='Ouvrir l’article (déploiement à vérifier)';row.append(a);}}root.append(textNode('h3','Derniers traitements'));for(const run of runs.workflow_runs){const row=document.createElement('p'),a=document.createElement('a');a.href=run.html_url;a.target='_blank';a.rel='noopener';a.textContent=run.name+' · '+(run.conclusion||run.status)+' · '+new Date(run.created_at).toLocaleString('fr-FR');row.append(a);root.append(row);}const a=document.createElement('a');a.href='/bons-plans.html';a.target='_blank';a.textContent='Voir les bons plans en ligne';root.append(a);});
$('preview-desktop').onclick=()=>{$('preview-content').classList.remove('mobile-preview');};$('preview-mobile').onclick=()=>{$('preview-content').classList.add('mobile-preview');};
// Exact renderer runs privately; artifact is downloaded from GitHub, never from a public draft URL.
$('preview-exact').onclick=()=>task(async()=>{await dispatch('preview.yml');$('exact-status').textContent='Aperçu final demandé. Téléchargez apercu-prive dans le traitement GitHub, puis ouvrez apercu.html. Cet aperçu utilise exactement le rendu du site.';});
const metadataCache=new Map();
const originalRefresh=refreshList;refreshList=async function(){await originalRefresh();await Promise.all(entries.filter(e=>e.name.endsWith('.json')).map(async e=>{const cached=metadataCache.get(e.path);if(cached&&cached.sha===e.sha)return;try{const f=await api('/contents/'+e.path+'?ref=main');const d=JSON.parse(decode(f.content));metadataCache.set(e.path,{sha:e.sha,title:d.title||d.message?.split('\n')[0]||e.name,categories:d.categories||[],published:d.published});}catch{}}));drawList();};
drawList=function(){const q=$('search').value.toLowerCase(),list=$('drafts');list.replaceChildren();for(const e of entries.filter(x=>x.name.endsWith('.json'))){const meta=metadataCache.get(e.path),title=meta?.title||e.name.replace(/\.json$/,'').replace(/-/g,' ');if(![title,e.name,...(meta?.categories||[])].join(' ').toLowerCase().includes(q))continue;const b=action(title,()=>task(async()=>{if(unsaved()&&!confirm('Changer de contenu sans enregistrer ?'))return;const file=await api('/contents/'+e.path+'?ref=main');current={path:e.path,sha:file.sha};paint(JSON.parse(decode(file.content)));status('Contenu ouvert.');}));b.dataset.path=e.path;b.title=(meta?.categories||[]).join(', ');list.append(b);}};
const previousSaved=window.editorSaved;window.editorSaved=()=>{metadataCache.delete(current?.path);previousSaved();};
let galleryTarget=null;
// A gallery reuses the media chooser and accepts several images before closing.
const previousBlocks=$('blocks').onclick;$('blocks').onclick=()=>{previousBlocks();const root=$('tools-content');const select=root.querySelector('select');const buttons=root.querySelectorAll('button');const submit=buttons[buttons.length-1];const old=submit.onclick;submit.onclick=()=>{if(select.value!=='gallery'){old();return;}const node=document.createElement('div');node.className='dt-gallery';insert(node);$('tools-dialog').close();setTimeout(()=>{galleryTarget=node;$('media-library').click();},0);};};
// Enhance existing media actions after drawing, without changing their stored path.
const previousMedia=$('media-library').onclick;$('media-library').onclick=()=>{previousMedia();};
const mediaObserver=new MutationObserver(()=>{if(!galleryTarget||!galleryTarget.isConnected)return;const grid=$('tools-content').querySelector('.media-grid');if(!grid)return;for(const row of grid.querySelectorAll('section')){const b=[...row.querySelectorAll('button')].find(b=>b.textContent==='Insérer');if(!b||b.dataset.galleryBound)continue;b.dataset.galleryBound='1';b.onclick=()=>{const name=row.querySelector('p').textContent;if(/\.(mp4|webm)$/i.test(name)){status('Choisissez une image pour cette galerie.',true);return;}const fig=document.createElement('figure'),img=document.createElement('img');img.src='/media/'+name;img.alt='';fig.append(img);galleryTarget.append(fig);privateImages();changed();b.textContent='Ajoutée';b.disabled=true;};}});mediaObserver.observe($('tools-content'),{childList:true,subtree:true});
$('tools-dialog').addEventListener('close',()=>{galleryTarget=null;});
async function unzipHTML(buffer){const bytes=new Uint8Array(buffer),view=new DataView(buffer);let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw Error('Archive invalide.');let offset=view.getUint32(end+16,true);const count=view.getUint16(end+10,true);for(let i=0;i<count;i++){if(view.getUint32(offset,true)!==0x02014b50)throw Error('Archive invalide.');const method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),length=view.getUint16(offset+28,true),extra=view.getUint16(offset+30,true),comment=view.getUint16(offset+32,true),local=view.getUint32(offset+42,true),name=new TextDecoder().decode(bytes.slice(offset+46,offset+46+length));if(name.endsWith('apercu.html')){const start=local+30+view.getUint16(local+26,true)+view.getUint16(local+28,true),packed=bytes.slice(start,start+size);if(method===0)return new TextDecoder().decode(packed);if(method!==8)throw Error('Compression non prise en charge.');const stream=new Blob([packed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Response(stream).text();}offset+=46+length+extra+comment;}throw Error('apercu.html absent.');}
function displayExactHTML(html){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,object,embed,form,svg,math').forEach(n=>n.remove());doc.querySelectorAll('iframe').forEach(n=>{try{const u=new URL(n.getAttribute('src'));if(!['https://www.youtube-nocookie.com','https://player.vimeo.com','https://www.dailymotion.com'].includes(u.origin))n.remove();else{n.removeAttribute('srcdoc');n.referrerPolicy='no-referrer';}}catch{n.remove();}});const policy=doc.createElement('meta');policy.httpEquiv='Content-Security-Policy';policy.content="default-src 'none'; script-src 'none'; img-src data: blob:; media-src data: blob: https:; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com; style-src 'unsafe-inline'; font-src data:; base-uri 'none'; form-action 'none'";doc.head.prepend(policy);doc.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes])if(a.name.startsWith('on'))n.removeAttribute(a.name);});if(exactFrameURL)URL.revokeObjectURL(exactFrameURL);exactFrameURL=URL.createObjectURL(new Blob(['<!doctype html>'+doc.documentElement.outerHTML],{type:'text/html'}));const frame=document.createElement('iframe');frame.sandbox='allow-scripts';frame.title='Aperçu final du site';frame.src=exactFrameURL;$('preview-content').replaceChildren(frame);$('exact-status').textContent='Rendu final chargé. Choisissez PC ou Mobile.';}
$('preview-exact').onclick=()=>task(async()=>{if(mode!=='articles')throw Error('L’aperçu final concerne les articles.');const workflow='preview.yml',baseline=await api('/actions/workflows/'+workflow+'/runs?per_page=10'),ids=new Set(baseline.workflow_runs.map(x=>x.id));await dispatch(workflow);$('exact-status').textContent='Génération privée en cours… Vous pouvez continuer à écrire.';let attempts=0;const path=current.path;async function follow(){try{const runs=await api('/actions/workflows/'+workflow+'/runs?per_page=10');const run=runs.workflow_runs.find(x=>!ids.has(x.id)&&x.event==='workflow_dispatch'&&x.display_title?.includes(path));if(run?.status==='completed'){if(run.conclusion!=='success')throw Error('La génération a échoué : ouvrez le traitement GitHub pour voir le motif.');const artifacts=await api('/actions/runs/'+run.id+'/artifacts'),artifact=artifacts.artifacts.find(x=>x.name==='apercu-prive'&&!x.expired);if(!artifact)throw Error('Fichier d’aperçu absent.');try{const response=await fetch(API+'/actions/artifacts/'+artifact.id+'/zip',{signal:AbortSignal.timeout(25000),headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token}});if(!response.ok)throw Error('Téléchargement refusé');displayExactHTML(await unzipHTML(await response.arrayBuffer()));}catch{$('exact-status').textContent='Aperçu généré. Le navigateur bloque son téléchargement automatique. Téléchargez apercu-prive via « Suivre le traitement », puis importez le ZIP ou apercu.html ici.';}return;}if(++attempts>=36)throw Error('Le traitement prend plus de trois minutes. Consultez « Suivre le traitement ».');setTimeout(follow,5000);}catch(e){$('exact-status').textContent=e.message;}}setTimeout(follow,3000);});
$('preview-file').onchange=()=>task(async()=>{const file=$('preview-file').files[0];if(!file)return;if(file.size>100*1024*1024)throw Error('Aperçu supérieur à 100 Mo.');displayExactHTML(file.name.endsWith('.zip')?await unzipHTML(await file.arrayBuffer()):await file.text());$('preview-file').value='';});

$('image-remove').onclick=()=>{
 if(!selectedImage||!$('body').contains(selectedImage)){status('Cliquez sur l’image à supprimer dans le texte.',true);return;}
 const image=selectedImage,figure=image.closest('figure'),parent=image.parentElement;
 if(figure&&figure.querySelectorAll('img,video,iframe').length===1){
  const check=figure.cloneNode(true);check.querySelectorAll('img,figcaption').forEach(n=>n.remove());
  if(!check.textContent.trim())figure.remove();else image.remove();
 }else image.remove();
 if(parent?.tagName==='A'&&!parent.textContent.trim()&&!parent.children.length)parent.remove();
 selectedImage=null;range=null;changed();$('image-tools-dialog').close();
 status('Image retirée du texte. Elle reste disponible dans la médiathèque.');
};
